/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/Media/Avatar/Avatar.vue')['default']
    'Avatar.story': typeof import('./components/Media/Avatar/Avatar.story.vue')['default']
    BulletPoints: typeof import('./components/Indicators/BulletPoints/BulletPoints.vue')['default']
    'BulletPoints.story': typeof import('./components/Indicators/BulletPoints/BulletPoints.story.vue')['default']
    Button: typeof import('./components/CTA/Button/Button.vue')['default']
    'Button.story': typeof import('./components/CTA/Button/Button.story.vue')['default']
    CertifContainer: typeof import('./components/Containment/CertifContainer/CertifContainer.vue')['default']
    'CertifContainer.story': typeof import('./components/Containment/CertifContainer/CertifContainer.story.vue')['default']
    CheckBox: typeof import('./components/CTA/CheckBox/CheckBox.vue')['default']
    'CheckBox.story': typeof import('./components/CTA/CheckBox/CheckBox.story.vue')['default']
    ChipContainer: typeof import('./components/Containment/ChipContainer/ChipContainer.vue')['default']
    'ChipContainer.story': typeof import('./components/Containment/ChipContainer/ChipContainer.story.vue')['default']
    ControlDescription: typeof import('./../histoire/components/internals/ControlDescription.vue')['default']
    DeleteModal: typeof import('./components/Indicators/DeleteModal/DeleteModal.vue')['default']
    'DeleteModal.story': typeof import('./components/Indicators/DeleteModal/DeleteModal.story.vue')['default']
    IconsBase: typeof import('./components/Media/IconsBase/IconsBase.vue')['default']
    'IconsBase.story': typeof import('./components/Media/IconsBase/IconsBase.story.vue')['default']
    InputField: typeof import('./components/CTA/InputField/InputField.vue')['default']
    'InputField.story': typeof import('./components/CTA/InputField/InputField.story.vue')['default']
    Loader: typeof import('./components/Indicators/Loader/Loader.vue')['default']
    'Loader.story': typeof import('./components/Indicators/Loader/Loader.story.vue')['default']
    RankingContainer: typeof import('./components/Containment/RankingContainer/RankingContainer.vue')['default']
    'RankingContainer.story': typeof import('./components/Containment/RankingContainer/RankingContainer.story.vue')['default']
    SelectField: typeof import('./components/CTA/SelectField/SelectField.vue')['default']
    'SelectField.story': typeof import('./components/CTA/SelectField/SelectField.story.vue')['default']
    SnackBar: typeof import('./components/Indicators/SnackBar/SnackBar.vue')['default']
    'SnackBar.story': typeof import('./components/Indicators/SnackBar/SnackBar.story.vue')['default']
    StepIndicator: typeof import('./components/Indicators/StepIndicator/StepIndicator.vue')['default']
    'StepIndicator.story': typeof import('./components/Indicators/StepIndicator/StepIndicator.story.vue')['default']
    ToggleButton: typeof import('./components/CTA/ToggleButton/ToggleButton.vue')['default']
    'ToggleButton.story': typeof import('./components/CTA/ToggleButton/ToggleButton.story.vue')['default']
    VideoPlayer: typeof import('./components/Media/VideoPlayer/VideoPlayer.vue')['default']
    'VideoPlayer.story': typeof import('./components/Media/VideoPlayer/VideoPlayer.story.vue')['default']
  }
}
