/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BulletPoints: typeof import('./components/Indicators/bulletPoints/bulletPoints.vue')['default']
    'BulletPoints.story': typeof import('./components/Indicators/bulletPoints/bulletPoints.story.vue')['default']
    ControlDescription: typeof import('./../histoire/components/internals/ControlDescription.vue')['default']
    Loader: typeof import('./components/Indicators/Loader/Loader.vue')['default']
    'Loader.story': typeof import('./components/Indicators/Loader/Loader.story.vue')['default']
  }
}
